services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                user: snipto
                uid: 1000
                APP_ENV: '${APP_ENV:-production}'
        image: snipto/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8080}:${APP_PORT:-8080}'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            LARAVEL_SAIL: 1
            APP_ENV: '${APP_ENV:-production}'
            APP_PORT: '${APP_PORT:-8080}'
            DB_CONNECTION: '${DB_CONNECTION:-mysql}'
            DB_HOST: '${DB_HOST:-mariadb}'
            DB_PORT: '${DB_PORT:-3306}'
            DB_DATABASE: '${DB_DATABASE:-snipto}'
            DB_USERNAME: '${DB_USERNAME:-snipto}'
            DB_PASSWORD: '${DB_PASSWORD:-secret}'
            XDEBUG_MODE: 'debug,develop'
            XDEBUG_CONFIG: 'client_host=host.docker.internal client_port=9003 start_with_request=yes'
            PHP_IDE_CONFIG: 'serverName=Snipto'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
    mariadb:
        image: 'mariadb:11'
        profiles: ["with-db"]
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-snipto}'
            MYSQL_USER: '${DB_USERNAME:-snipto}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
networks:
    sail:
        driver: bridge
volumes:
    sail-mariadb:
        driver: local
