#!/bin/bash
# generate-cloudflare-nginx-config.sh
# Fetches Cloudflare's current IP ranges and generates an nginx config file
# that handles both access control (geo block) and real IP translation.
#
# Usage: ./generate-cloudflare-nginx-config.sh [output_path]
#   output_path defaults to docker/cloudflare.conf (relative to repo root)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

OUTPUT_PATH="${1:-$REPO_ROOT/docker/cloudflare.conf}"

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT_PATH")"

echo "Fetching Cloudflare IP ranges..."

# Fetch IPv4 and IPv6 ranges from Cloudflare's official sources
CF_IPV4=$(curl -s https://www.cloudflare.com/ips-v4)
CF_IPV6=$(curl -s https://www.cloudflare.com/ips-v6)

if [ -z "$CF_IPV4" ] || [ -z "$CF_IPV6" ]; then
    echo "ERROR: Failed to fetch Cloudflare IP ranges. Check your network connection." >&2
    exit 1
fi

# Count ranges for reporting
IPV4_COUNT=$(echo "$CF_IPV4" | wc -l)
IPV6_COUNT=$(echo "$CF_IPV6" | wc -l)
TOTAL=$((IPV4_COUNT + IPV6_COUNT))

echo "Found $IPV4_COUNT IPv4 and $IPV6_COUNT IPv6 ranges ($TOTAL total)"

# Generate the nginx config file
cat > "$OUTPUT_PATH" << 'HEADER'
# cloudflare.conf — Auto-generated by generate-cloudflare-nginx-config.sh
# DO NOT EDIT MANUALLY. Run this script to update when Cloudflare changes their IP ranges.
#
# This file serves two purposes:
#   1. geo block: Checks the connection IP (Cloudflare's) BEFORE real IP translation
#   2. set_real_ip_from + real_ip_header: Translates $remote_addr for logging after access is granted

HEADER

# Write the geo block (access control — checks Cloudflare IPs before translation)
echo 'geo $cf_trusted {' >> "$OUTPUT_PATH"
echo '    default 0;' >> "$OUTPUT_PATH"

for cidr in $CF_IPV4; do
    echo "    ${cidr}   1;" >> "$OUTPUT_PATH"
done

for cidr in $CF_IPV6; do
    echo "    ${cidr}    1;" >> "$OUTPUT_PATH"
done

echo '}' >> "$OUTPUT_PATH"
echo '' >> "$OUTPUT_PATH"

# Write the set_real_ip_from directives (real IP translation for logging)
echo '# Real IP translation — runs AFTER geo block checks' >> "$OUTPUT_PATH"
for cidr in $CF_IPV4; do
    echo "set_real_ip_from ${cidr};" >> "$OUTPUT_PATH"
done

for cidr in $CF_IPV6; do
    echo "set_real_ip_from ${cidr};" >> "$OUTPUT_PATH"
done

echo '' >> "$OUTPUT_PATH"
echo 'real_ip_header CF-Connecting-IP;' >> "$OUTPUT_PATH"

# Add a footer with metadata and reload instruction
cat >> "$OUTPUT_PATH" << FOOTER

# --- Metadata ---
# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# IPv4 ranges: $IPV4_COUNT | IPv6 ranges: $IPV6_COUNT | Total: $TOTAL
# Source: https://www.cloudflare.com/ips/
#
# After updating, reload nginx:
#   docker exec snipto-nginx-1 nginx -s reload
FOOTER

echo "Config written to $OUTPUT_PATH"
echo "IPv4 ranges: $IPV4_COUNT | IPv6 ranges: $IPV6_COUNT | Total: $TOTAL"
echo ""
echo "To apply the changes, run:"
echo "  docker exec snipto-nginx-1 nginx -s reload"
